name: Test Disconnected CSV
on:
  push:
    paths:
      - disconnected-csv/**
      - .github/workflows/disconnected-csv.yaml

  pull_request:
    paths:
      - disconnected-csv/**
      - .github/workflows/disconnected-csv.yaml

# Declare default permissions as read only.
permissions: read-all

jobs:
  disconnected-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: disconnected-csv/Dockerfile
          ignore: DL3013 # https://github.com/hadolint/hadolint/wiki/DL3013

      - uses: ./disconnected-csv
        with:
          CSV_FILE: ./disconnected-csv/tests/sample-clusterserviceversion.yaml
          TAGS_TO_DIGESTS: 1
