name: Build ssh-agent

on:
  push:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**
  pull_request:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: |
          pushd ssh-agent/
          npm install
          popd

      - name: Run linters
        run: |
          pushd ssh-agent/
          npm run prettier
          npm run eslint
          popd

      - name: Compile Node.js dependencies
        run: |
          pushd ssh-agent/
          npm run compile
          popd