name: Build ssh-agent

on:
  push:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**
  pull_request:
    paths:
      - .github/workflows/ssh-agent-build.yaml
      - ssh-agent/**

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: |
          pushd ssh-agent/
          npm ci
          popd

      - name: Run linters
        run: |
          pushd ssh-agent/
          npm run prettier
          npm run eslint
          popd

      - name: Compile Node.js dependencies
        run: |
          pushd ssh-agent/
          npm run compile
          popd